[package]
name = "asciibar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", default-features = false, features = ["std", "help", "cargo", "derive", "error-context"] }
anyhow = "1.0.68"
